name: Move assigned card
on:
  issues:
    types:
      - assigned
jobs:
  move-assigned-card:
    runs-on: ubuntu-latest
    steps:
      - name: Move To In Progress
        uses: alex-page/github-project-automation-plus@v0.8.3
        with:
          project: Fibonacci
          column: In Progress
          repo-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
